@extends('layout')

@section('banner')
  <div class="photos banner">
    <section class="small-wrapper">
      <h1 class="large-heading">{{ $pageName }}</h1>
    </section>
  </div>
@stop

@section('content')
  <div class="photos-nav">
    <div class="small-wrapper">
      <ul>
        <li><a href="/photos/2016-summer-event">2016 Summer Tasting</a></li>
        <li class="active"><a href="/photos/2015-fall-event">2015 Fall Tasting</a></li>
        <li><a href="/photos/2015-fall-meeting">2015 Fall Committee Meeting</a></li>
        <li><a href="/photos/2015-winter-event">2015 Winter Tasting</a></li>
      </ul>
    </div>
  </div>
  <div class="small-wrapper photos-content">
    <section class="photo-section mb-40 mt-30 bottom-border">
      <h2 class="main-heading mb-40">2015 Fall Tasting</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_001_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_001_.jpg') }}" alt="2015 Fall Event at the Foundry Image 1"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_002_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_002_.jpg') }}" alt="2015 Fall Event at the Foundry Image 2"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_003_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_003_.jpg') }}" alt="2015 Fall Event at the Foundry Image 3"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_004_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_004_.jpg') }}" alt="2015 Fall Event at the Foundry Image 4"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_005_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_005_.jpg') }}" alt="2015 Fall Event at the Foundry Image 5"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_006_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_006_.jpg') }}" alt="2015 Fall Event at the Foundry Image 6"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_007_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_007_.jpg') }}" alt="2015 Fall Event at the Foundry Image 7"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_008_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_008_.jpg') }}" alt="2015 Fall Event at the Foundry Image 8"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_009_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_009_.jpg') }}" alt="2015 Fall Event at the Foundry Image 9"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_010_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_010_.jpg') }}" alt="2015 Fall Event at the Foundry Image 10"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_011_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_011_.jpg') }}" alt="2015 Fall Event at the Foundry Image 11"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_012_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_012_.jpg') }}" alt="2015 Fall Event at the Foundry Image 12"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_014_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_014_.jpg') }}" alt="2015 Fall Event at the Foundry Image 13"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_015_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_015_.jpg') }}" alt="2015 Fall Event at the Foundry Image 14"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_016_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_016_.jpg') }}" alt="2015 Fall Event at the Foundry Image 15"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_017_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_017_.jpg') }}" alt="2015 Fall Event at the Foundry Image 16"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_018_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_018_.jpg') }}" alt="2015 Fall Event at the Foundry Image 17"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_019_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_019_.jpg') }}" alt="2015 Fall Event at the Foundry Image 18"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_020_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_020_.jpg') }}" alt="2015 Fall Event at the Foundry Image 19"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_021_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_021_.jpg') }}" alt="2015 Fall Event at the Foundry Image 20"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_022_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_022_.jpg') }}" alt="2015 Fall Event at the Foundry Image 21"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_023_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_023_.jpg') }}" alt="2015 Fall Event at the Foundry Image 22"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_024_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_024_.jpg') }}" alt="2015 Fall Event at the Foundry Image 23"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_025_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_025_.jpg') }}" alt="2015 Fall Event at the Foundry Image 24"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_026_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_026_.jpg') }}" alt="2015 Fall Event at the Foundry Image 25"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_027_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_027_.jpg') }}" alt="2015 Fall Event at the Foundry Image 26"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_028_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_028_.jpg') }}" alt="2015 Fall Event at the Foundry Image 27"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_029_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_029_.jpg') }}" alt="2015 Fall Event at the Foundry Image 28"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_030_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_030_.jpg') }}" alt="2015 Fall Event at the Foundry Image 29"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_031_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_031_.jpg') }}" alt="2015 Fall Event at the Foundry Image 30"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_032_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_032_.jpg') }}" alt="2015 Fall Event at the Foundry Image 31"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_034_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_034_.jpg') }}" alt="2015 Fall Event at the Foundry Image 32"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_035_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_035_.jpg') }}" alt="2015 Fall Event at the Foundry Image 33"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_036_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_036_.jpg') }}" alt="2015 Fall Event at the Foundry Image 34"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_037_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_037_.jpg') }}" alt="2015 Fall Event at the Foundry Image 35"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_038_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_038_.jpg') }}" alt="2015 Fall Event at the Foundry Image 36"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_039_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_039_.jpg') }}" alt="2015 Fall Event at the Foundry Image 37"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_040_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_040_.jpg') }}" alt="2015 Fall Event at the Foundry Image 38"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2015 Fall Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_021_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_021_.jpg') }}" alt="2015 Fall Event at the Foundry Image 39"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_022_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_022_.jpg') }}" alt="2015 Fall Event at the Foundry Image 40"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_023_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_023_.jpg') }}" alt="2015 Fall Event at the Foundry Image 41"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_024_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_024_.jpg') }}" alt="2015 Fall Event at the Foundry Image 42"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_025_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_025_.jpg') }}" alt="2015 Fall Event at the Foundry Image 43"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_026_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_026_.jpg') }}" alt="2015 Fall Event at the Foundry Image 44"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_027_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_027_.jpg') }}" alt="2015 Fall Event at the Foundry Image 45"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_028_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_028_.jpg') }}" alt="2015 Fall Event at the Foundry Image 46"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_029_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_029_.jpg') }}" alt="2015 Fall Event at the Foundry Image 47"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_030_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_030_.jpg') }}" alt="2015 Fall Event at the Foundry Image 48"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_031_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_031_.jpg') }}" alt="2015 Fall Event at the Foundry Image 49"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_032_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_032_.jpg') }}" alt="2015 Fall Event at the Foundry Image 50"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_034_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_034_.jpg') }}" alt="2015 Fall Event at the Foundry Image 51"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_035_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_035_.jpg') }}" alt="2015 Fall Event at the Foundry Image 52"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_036_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_036_.jpg') }}" alt="2015 Fall Event at the Foundry Image 53"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_037_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_037_.jpg') }}" alt="2015 Fall Event at the Foundry Image 54"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_038_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_038_.jpg') }}" alt="2015 Fall Event at the Foundry Image 55"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_039_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_039_.jpg') }}" alt="2015 Fall Event at the Foundry Image 56"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_040_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_040_.jpg') }}" alt="2015 Fall Event at the Foundry Image 57"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2015 Fall Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_041_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_041_.jpg') }}" alt="2015 Fall Event at the Foundry Image 58"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_042_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_042_.jpg') }}" alt="2015 Fall Event at the Foundry Image 59"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_043_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_043_.jpg') }}" alt="2015 Fall Event at the Foundry Image 60"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_044_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_044_.jpg') }}" alt="2015 Fall Event at the Foundry Image 61"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_045_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_045_.jpg') }}" alt="2015 Fall Event at the Foundry Image 62"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_046_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_046_.jpg') }}" alt="2015 Fall Event at the Foundry Image 63"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_047_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_047_.jpg') }}" alt="2015 Fall Event at the Foundry Image 64"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_048_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_048_.jpg') }}" alt="2015 Fall Event at the Foundry Image 65"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_049_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_049_.jpg') }}" alt="2015 Fall Event at the Foundry Image 66"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_050_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_050_.jpg') }}" alt="2015 Fall Event at the Foundry Image 67"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_051_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_051_.jpg') }}" alt="2015 Fall Event at the Foundry Image 68"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_052_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_052_.jpg') }}" alt="2015 Fall Event at the Foundry Image 69"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_054_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_054_.jpg') }}" alt="2015 Fall Event at the Foundry Image 70"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_055_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_055_.jpg') }}" alt="2015 Fall Event at the Foundry Image 71"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_056_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_056_.jpg') }}" alt="2015 Fall Event at the Foundry Image 72"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_057_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_057_.jpg') }}" alt="2015 Fall Event at the Foundry Image 73"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_058_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_058_.jpg') }}" alt="2015 Fall Event at the Foundry Image 74"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_059_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_059_.jpg') }}" alt="2015 Fall Event at the Foundry Image 75"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_060_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_060_.jpg') }}" alt="2015 Fall Event at the Foundry Image 76"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2015 Fall Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_061_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_061_.jpg') }}" alt="2015 Fall Event at the Foundry Image 77"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_062_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_062_.jpg') }}" alt="2015 Fall Event at the Foundry Image 78"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_063_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_063_.jpg') }}" alt="2015 Fall Event at the Foundry Image 79"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_064_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_064_.jpg') }}" alt="2015 Fall Event at the Foundry Image 80"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_065_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_065_.jpg') }}" alt="2015 Fall Event at the Foundry Image 81"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_066_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_066_.jpg') }}" alt="2015 Fall Event at the Foundry Image 82"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_067_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_067_.jpg') }}" alt="2015 Fall Event at the Foundry Image 83"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_068_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_068_.jpg') }}" alt="2015 Fall Event at the Foundry Image 84"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_069_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_069_.jpg') }}" alt="2015 Fall Event at the Foundry Image 85"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_070_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_070_.jpg') }}" alt="2015 Fall Event at the Foundry Image 86"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_071_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_071_.jpg') }}" alt="2015 Fall Event at the Foundry Image 87"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_072_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_072_.jpg') }}" alt="2015 Fall Event at the Foundry Image 88"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_074_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_074_.jpg') }}" alt="2015 Fall Event at the Foundry Image 89"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_075_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_075_.jpg') }}" alt="2015 Fall Event at the Foundry Image 90"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_076_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_076_.jpg') }}" alt="2015 Fall Event at the Foundry Image 91"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_077_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_077_.jpg') }}" alt="2015 Fall Event at the Foundry Image 92"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_078_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_078_.jpg') }}" alt="2015 Fall Event at the Foundry Image 93"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_079_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_079_.jpg') }}" alt="2015 Fall Event at the Foundry Image 94"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_080_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_080_.jpg') }}" alt="2015 Fall Event at the Foundry Image 95"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2015 Fall Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_081_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_081_.jpg') }}" alt="2015 Fall Event at the Foundry Image 96"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_082_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_082_.jpg') }}" alt="2015 Fall Event at the Foundry Image 97"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_083_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_083_.jpg') }}" alt="2015 Fall Event at the Foundry Image 98"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_084_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_084_.jpg') }}" alt="2015 Fall Event at the Foundry Image 99"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_085_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_085_.jpg') }}" alt="2015 Fall Event at the Foundry Image 100"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_086_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_086_.jpg') }}" alt="2015 Fall Event at the Foundry Image 101"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_087_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_087_.jpg') }}" alt="2015 Fall Event at the Foundry Image 102"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_088_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_088_.jpg') }}" alt="2015 Fall Event at the Foundry Image 103"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_089_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_089_.jpg') }}" alt="2015 Fall Event at the Foundry Image 104"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_090_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_090_.jpg') }}" alt="2015 Fall Event at the Foundry Image 105"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_091_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_091_.jpg') }}" alt="2015 Fall Event at the Foundry Image 106"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_092_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_092_.jpg') }}" alt="2015 Fall Event at the Foundry Image 107"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_094_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_094_.jpg') }}" alt="2015 Fall Event at the Foundry Image 108"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_096_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_096_.jpg') }}" alt="2015 Fall Event at the Foundry Image 109"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_097_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_097_.jpg') }}" alt="2015 Fall Event at the Foundry Image 110"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_098_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_098_.jpg') }}" alt="2015 Fall Event at the Foundry Image 111"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_099_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_099_.jpg') }}" alt="2015 Fall Event at the Foundry Image 112"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_100_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_100_.jpg') }}" alt="2015 Fall Event at the Foundry Image 113"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2015 Fall Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_101_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_101_.jpg') }}" alt="2015 Fall Event at the Foundry Image 114"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_103_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_103_.jpg') }}" alt="2015 Fall Event at the Foundry Image 115"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_105_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_105_.jpg') }}" alt="2015 Fall Event at the Foundry Image 116"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_106_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_106_.jpg') }}" alt="2015 Fall Event at the Foundry Image 117"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_108_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_108_.jpg') }}" alt="2015 Fall Event at the Foundry Image 118"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_110_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_110_.jpg') }}" alt="2015 Fall Event at the Foundry Image 119"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_112_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_112_.jpg') }}" alt="2015 Fall Event at the Foundry Image 120"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_115_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_115_.jpg') }}" alt="2015 Fall Event at the Foundry Image 121"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_117_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_117_.jpg') }}" alt="2015 Fall Event at the Foundry Image 122"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_118_.jpg') }}" data-lightbox="image-1" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2015-Fall-Foundry/Uncorked_Fall_2015_118_.jpg') }}" alt="2015 Fall Event at the Foundry Image 123"></a></li>
      </ul>
    </section>
  </div>
@stop