@extends('layout')

@section('banner')
  <div class="photos banner">
    <section class="small-wrapper">
      <h1 class="large-heading">{{ $pageName }}</h1>
    </section>
  </div>
@stop

@section('content')
  <div class="photos-nav">
    <div class="small-wrapper">
      <ul>
        <li class="active"><a href="/photos/2016-summer-event">2016 Summer Tasting</a></li>
        <li><a href="/photos/2015-fall-event">2015 Fall Tasting</a></li>
        <li><a href="/photos/2015-fall-meeting">2015 Fall Committee Meeting</a></li>
        <li><a href="/photos/2015-winter-event">2015 Winter Tasting</a></li>
      </ul>
    </div>
  </div>
  <div class="small-wrapper photos-content">
    <section class="photo-section mb-40 mt-30 bottom-border">
      <h2 class="main-heading mb-40">2016 Summer Tasting</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-1.jpg') }}" data-lightbox="image-1" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-1.jpg') }}" alt="Summer 2016 Event Image 1"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-2.jpg') }}" data-lightbox="image-2" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-2.jpg') }}" alt="Summer 2016 Event Image 2"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-3.jpg') }}" data-lightbox="image-3" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-3.jpg') }}" alt="Summer 2016 Event Image 3"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-4.jpg') }}" data-lightbox="image-4" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-4.jpg') }}" alt="Summer 2016 Event Image 4"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-5.jpg') }}" data-lightbox="image-5" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-5.jpg') }}" alt="Summer 2016 Event Image 5"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-6.jpg') }}" data-lightbox="image-6" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-6.jpg') }}" alt="Summer 2016 Event Image 6"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-7.jpg') }}" data-lightbox="image-7" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-7.jpg') }}" alt="Summer 2016 Event Image 7"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-8.jpg') }}" data-lightbox="image-8" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-8.jpg') }}" alt="Summer 2016 Event Image 8"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-9.jpg') }}" data-lightbox="image-9" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-9.jpg') }}" alt="Summer 2016 Event Image 9"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-10.jpg') }}" data-lightbox="image-10" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-10.jpg') }}" alt="Summer 2016 Event Image 10"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-11.jpg') }}" data-lightbox="image-11" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-11.jpg') }}" alt="Summer 2016 Event Image 11"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-12.jpg') }}" data-lightbox="image-12" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-12.jpg') }}" alt="Summer 2016 Event Image 12"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-13.jpg') }}" data-lightbox="image-13" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-13.jpg') }}" alt="Summer 2016 Event Image 13"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-14.jpg') }}" data-lightbox="image-14" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-14.jpg') }}" alt="Summer 2016 Event Image 14"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-15.jpg') }}" data-lightbox="image-15" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-15.jpg') }}" alt="Summer 2016 Event Image 15"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-16.jpg') }}" data-lightbox="image-16" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-16.jpg') }}" alt="Summer 2016 Event Image 16"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-17.jpg') }}" data-lightbox="image-17" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-17.jpg') }}" alt="Summer 2016 Event Image 17"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-18.jpg') }}" data-lightbox="image-18" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-18.jpg') }}" alt="Summer 2016 Event Image 18"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-19.jpg') }}" data-lightbox="image-19" data-title="2016 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-19.jpg') }}" alt="Summer 2016 Event Image 19"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-20.jpg') }}" data-lightbox="image-20" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-20.jpg') }}" alt="Summer 2016 Event Image 20"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-21.jpg') }}" data-lightbox="image-21" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-21.jpg') }}" alt="Summer 2016 Event Image 21"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-22.jpg') }}" data-lightbox="image-22" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-22.jpg') }}" alt="Summer 2016 Event Image 22"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-23.jpg') }}" data-lightbox="image-23" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-23.jpg') }}" alt="Summer 2016 Event Image 23"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-24.jpg') }}" data-lightbox="image-24" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-24.jpg') }}" alt="Summer 2016 Event Image 24"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-25.jpg') }}" data-lightbox="image-25" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-25.jpg') }}" alt="Summer 2016 Event Image 25"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-26.jpg') }}" data-lightbox="image-26" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-26.jpg') }}" alt="Summer 2016 Event Image 26"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-27.jpg') }}" data-lightbox="image-27" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-27.jpg') }}" alt="Summer 2016 Event Image 27"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-28.jpg') }}" data-lightbox="image-28" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-28.jpg') }}" alt="Summer 2016 Event Image 28"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-29.jpg') }}" data-lightbox="image-29" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-29.jpg') }}" alt="Summer 2016 Event Image 29"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-30.jpg') }}" data-lightbox="image-30" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-30.jpg') }}" alt="Summer 2016 Event Image 30"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-31.jpg') }}" data-lightbox="image-31" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-31.jpg') }}" alt="Summer 2016 Event Image 31"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-32.jpg') }}" data-lightbox="image-32" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-32.jpg') }}" alt="Summer 2016 Event Image 32"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-33.jpg') }}" data-lightbox="image-33" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-33.jpg') }}" alt="Summer 2016 Event Image 33"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-34.jpg') }}" data-lightbox="image-34" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-34.jpg') }}" alt="Summer 2016 Event Image 34"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-35.jpg') }}" data-lightbox="image-35" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-35.jpg') }}" alt="Summer 2016 Event Image 35"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-36.jpg') }}" data-lightbox="image-36" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-36.jpg') }}" alt="Summer 2016 Event Image 36"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-37.jpg') }}" data-lightbox="image-37" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-37.jpg') }}" alt="Summer 2016 Event Image 37"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-38.jpg') }}" data-lightbox="image-38" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-38.jpg') }}" alt="Summer 2016 Event Image 38"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2016 Summer Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-39.jpg') }}" data-lightbox="image-39" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-39.jpg') }}" alt="Summer 2016 Event Image 39"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-40.jpg') }}" data-lightbox="image-40" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-40.jpg') }}" alt="Summer 2016 Event Image 40"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-41.jpg') }}" data-lightbox="image-41" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-41.jpg') }}" alt="Summer 2016 Event Image 41"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-42.jpg') }}" data-lightbox="image-42" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-42.jpg') }}" alt="Summer 2016 Event Image 42"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-43.jpg') }}" data-lightbox="image-43" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-43.jpg') }}" alt="Summer 2016 Event Image 43"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-44.jpg') }}" data-lightbox="image-44" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-44.jpg') }}" alt="Summer 2016 Event Image 44"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-45.jpg') }}" data-lightbox="image-45" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-45.jpg') }}" alt="Summer 2016 Event Image 45"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-46.jpg') }}" data-lightbox="image-46" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-46.jpg') }}" alt="Summer 2016 Event Image 46"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-47.jpg') }}" data-lightbox="image-47" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-47.jpg') }}" alt="Summer 2016 Event Image 47"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-48.jpg') }}" data-lightbox="image-48" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-48.jpg') }}" alt="Summer 2016 Event Image 48"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-49.jpg') }}" data-lightbox="image-49" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-49.jpg') }}" alt="Summer 2016 Event Image 49"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-50.jpg') }}" data-lightbox="image-50" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-50.jpg') }}" alt="Summer 2016 Event Image 50"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-51.jpg') }}" data-lightbox="image-51" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-51.jpg') }}" alt="Summer 2016 Event Image 51"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-52.jpg') }}" data-lightbox="image-52" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-52.jpg') }}" alt="Summer 2016 Event Image 52"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-53.jpg') }}" data-lightbox="image-53" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-53.jpg') }}" alt="Summer 2016 Event Image 53"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-54.jpg') }}" data-lightbox="image-54" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-54.jpg') }}" alt="Summer 2016 Event Image 54"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-55.jpg') }}" data-lightbox="image-55" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-55.jpg') }}" alt="Summer 2016 Event Image 55"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-56.jpg') }}" data-lightbox="image-56" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-56.jpg') }}" alt="Summer 2016 Event Image 56"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-57.jpg') }}" data-lightbox="image-57" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-57.jpg') }}" alt="Summer 2016 Event Image 57"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2016 Summer Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-58.jpg') }}" data-lightbox="image-58" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-58.jpg') }}" alt="Summer 2016 Event Image 58"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-59.jpg') }}" data-lightbox="image-59" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-59.jpg') }}" alt="Summer 2016 Event Image 59"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-60.jpg') }}" data-lightbox="image-60" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-60.jpg') }}" alt="Summer 2016 Event Image 60"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-61.jpg') }}" data-lightbox="image-61" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-61.jpg') }}" alt="Summer 2016 Event Image 61"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-62.jpg') }}" data-lightbox="image-62" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-62.jpg') }}" alt="Summer 2016 Event Image 62"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-63.jpg') }}" data-lightbox="image-63" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-63.jpg') }}" alt="Summer 2016 Event Image 63"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-64.jpg') }}" data-lightbox="image-64" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-64.jpg') }}" alt="Summer 2016 Event Image 64"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-65.jpg') }}" data-lightbox="image-65" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-65.jpg') }}" alt="Summer 2016 Event Image 65"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-66.jpg') }}" data-lightbox="image-66" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-66.jpg') }}" alt="Summer 2016 Event Image 66"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-67.jpg') }}" data-lightbox="image-67" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-67.jpg') }}" alt="Summer 2016 Event Image 67"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-68.jpg') }}" data-lightbox="image-68" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-68.jpg') }}" alt="Summer 2016 Event Image 68"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-69.jpg') }}" data-lightbox="image-69" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-69.jpg') }}" alt="Summer 2016 Event Image 69"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-70.jpg') }}" data-lightbox="image-70" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-70.jpg') }}" alt="Summer 2016 Event Image 70"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-71.jpg') }}" data-lightbox="image-71" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-71.jpg') }}" alt="Summer 2016 Event Image 71"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-72.jpg') }}" data-lightbox="image-72" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-72.jpg') }}" alt="Summer 2016 Event Image 72"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-73.jpg') }}" data-lightbox="image-73" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-73.jpg') }}" alt="Summer 2016 Event Image 73"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-74.jpg') }}" data-lightbox="image-74" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-74.jpg') }}" alt="Summer 2016 Event Image 74"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-75.jpg') }}" data-lightbox="image-75" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-75.jpg') }}" alt="Summer 2016 Event Image 75"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-76.jpg') }}" data-lightbox="image-76" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-76.jpg') }}" alt="Summer 2016 Event Image 76"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40 bottom-border">
      <h2 class="main-heading mb-40">2016 Summer Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-77.jpg') }}" data-lightbox="image-77" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-77.jpg') }}" alt="Summer 2016 Event Image 77"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-78.jpg') }}" data-lightbox="image-78" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-78.jpg') }}" alt="Summer 2016 Event Image 78"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-79.jpg') }}" data-lightbox="image-79" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-79.jpg') }}" alt="Summer 2016 Event Image 79"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-80.jpg') }}" data-lightbox="image-80" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-80.jpg') }}" alt="Summer 2016 Event Image 80"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-81.jpg') }}" data-lightbox="image-81" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-81.jpg') }}" alt="Summer 2016 Event Image 81"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-82.jpg') }}" data-lightbox="image-82" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-82.jpg') }}" alt="Summer 2016 Event Image 82"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-83.jpg') }}" data-lightbox="image-83" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-83.jpg') }}" alt="Summer 2016 Event Image 83"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-84.jpg') }}" data-lightbox="image-84" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-84.jpg') }}" alt="Summer 2016 Event Image 84"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-85.jpg') }}" data-lightbox="image-85" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-85.jpg') }}" alt="Summer 2016 Event Image 85"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-86.jpg') }}" data-lightbox="image-86" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-86.jpg') }}" alt="Summer 2016 Event Image 86"></a></li>
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-87.jpg') }}" data-lightbox="image-87" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-87.jpg') }}" alt="Summer 2016 Event Image 87"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-88.jpg') }}" data-lightbox="image-88" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-88.jpg') }}" alt="Summer 2016 Event Image 88"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-89.jpg') }}" data-lightbox="image-89" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-89.jpg') }}" alt="Summer 2016 Event Image 89"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-90.jpg') }}" data-lightbox="image-90" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-90.jpg') }}" alt="Summer 2016 Event Image 90"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-91.jpg') }}" data-lightbox="image-91" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-91.jpg') }}" alt="Summer 2016 Event Image 91"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-92.jpg') }}" data-lightbox="image-92" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-92.jpg') }}" alt="Summer 2016 Event Image 92"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-93.jpg') }}" data-lightbox="image-93" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-93.jpg') }}" alt="Summer 2016 Event Image 93"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-94.jpg') }}" data-lightbox="image-94" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-94.jpg') }}" alt="Summer 2016 Event Image 94"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-95.jpg') }}" data-lightbox="image-95" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-95.jpg') }}" alt="Summer 2016 Event Image 95"></a></li>
      </ul>
    </section>

    <section class="photo-section mb-40">
      <h2 class="main-heading mb-40">2016 Summer Tasting Continued</h2>
      <ul class="photo-gallery-list">
        <li class="col-16"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-96.jpg') }}" data-lightbox="image-96" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-96.jpg') }}" alt="Summer 2016 Event Image 96"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-97.jpg') }}" data-lightbox="image-97" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-97.jpg') }}" alt="Summer 2016 Event Image 97"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-98.jpg') }}" data-lightbox="image-98" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-98.jpg') }}" alt="Summer 2016 Event Image 98"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-99.jpg') }}" data-lightbox="image-99" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-99.jpg') }}" alt="Summer 2016 Event Image 99"></a></li>
        <li class="col-8"><a href="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-100.jpg') }}" data-lightbox="image-100" data-title="2015 Fall Event At the Foundry"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2016-summer-event/Louisiville-Uncorked-100.jpg') }}" alt="Summer 2016 Event Image 100"></a></li>
      </ul>
    </section>
  </div>
@stop