@extends('layout')

@section('banner')
    <div class="photos banner">
        <section class="small-wrapper">
            <h1 class="large-heading">{{ $pageName }}</h1>
        </section>
    </div>
@stop

@section('content')
    <div class="photos-nav">
        <div class="small-wrapper">
            <ul>
                <li><a href="/photos/2018-winter-event">2018 Winter Tasting</a></li>
                <li class="active"><a href="/photos/2017-summer-event">2017 Summer Tasting</a></li>
                <li><a href="/photos/2017-winter-event">2017 Winter Tasting</a></li>
                <li><a href="/photos/2016-summer-event">2016 Summer Tasting</a></li>
                <li><a href="/photos/2015-fall-event">2015 Fall Tasting</a></li>
                <li><a href="/photos/2015-fall-meeting">2015 Fall Committee Meeting</a></li>
                <li><a href="/photos/2015-winter-event">2015 Winter Tasting</a></li>
            </ul>
        </div>
    </div>
    <div class="small-wrapper photos-content">
        <section class="photo-section mb-40 mt-30 bottom-border">
            <h2 class="main-heading mb-40">2017 Summer Tasting</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_001.jpg') }}" data-lightbox="image-1" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_001.jpg') }}" alt="Summer 2017 Event Image 1"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_002.jpg') }}" data-lightbox="image-2" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_002.jpg') }}" alt="Summer 2017 Event Image 2"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_003.jpg') }}" data-lightbox="image-3" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_003.jpg') }}" alt="Summer 2017 Event Image 3"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_004.jpg') }}" data-lightbox="image-4" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_004.jpg') }}" alt="Summer 2017 Event Image 4"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_005.jpg') }}" data-lightbox="image-5" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_005.jpg') }}" alt="Summer 2017 Event Image 5"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_006.jpg') }}" data-lightbox="image-6" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_006.jpg') }}" alt="Summer 2017 Event Image 6"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_007.jpg') }}" data-lightbox="image-7" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_007.jpg') }}" alt="Summer 2017 Event Image 7"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_008.jpg') }}" data-lightbox="image-8" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_008.jpg') }}" alt="Summer 2017 Event Image 8"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_009.jpg') }}" data-lightbox="image-9" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_009.jpg') }}" alt="Summer 2017 Event Image 9"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_010.jpg') }}" data-lightbox="image-10" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_010.jpg') }}" alt="Summer 2017 Event Image 10"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_011.jpg') }}" data-lightbox="image-11" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_011.jpg') }}" alt="Summer 2017 Event Image 11"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_012.jpg') }}" data-lightbox="image-12" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_012.jpg') }}" alt="Summer 2017 Event Image 12"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_013.jpg') }}" data-lightbox="image-13" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_013.jpg') }}" alt="Summer 2017 Event Image 13"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_014.jpg') }}" data-lightbox="image-14" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_014.jpg') }}" alt="Summer 2017 Event Image 14"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_015.jpg') }}" data-lightbox="image-15" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_015.jpg') }}" alt="Summer 2017 Event Image 15"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_016.jpg') }}" data-lightbox="image-16" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_016.jpg') }}" alt="Summer 2017 Event Image 16"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_017.jpg') }}" data-lightbox="image-17" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_017.jpg') }}" alt="Summer 2017 Event Image 17"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_018.jpg') }}" data-lightbox="image-18" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_018.jpg') }}" alt="Summer 2017 Event Image 18"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_019.jpg') }}" data-lightbox="image-19" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_019.jpg') }}" alt="Summer 2017 Event Image 19"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_020.jpg') }}" data-lightbox="image-20" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_020.jpg') }}" alt="Summer 2017 Event Image 20"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_021.jpg') }}" data-lightbox="image-21" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_021.jpg') }}" alt="Summer 2017 Event Image 21"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_022.jpg') }}" data-lightbox="image-22" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_022.jpg') }}" alt="Summer 2017 Event Image 22"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_023.jpg') }}" data-lightbox="image-23" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_023.jpg') }}" alt="Summer 2017 Event Image 23"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_024.jpg') }}" data-lightbox="image-24" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_024.jpg') }}" alt="Summer 2017 Event Image 24"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_025.jpg') }}" data-lightbox="image-25" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_025.jpg') }}" alt="Summer 2017 Event Image 25"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_026.jpg') }}" data-lightbox="image-26" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_026.jpg') }}" alt="Summer 2017 Event Image 26"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_027.jpg') }}" data-lightbox="image-27" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_027.jpg') }}" alt="Summer 2017 Event Image 27"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_028.jpg') }}" data-lightbox="image-28" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_028.jpg') }}" alt="Summer 2017 Event Image 28"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_029.jpg') }}" data-lightbox="image-29" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_029.jpg') }}" alt="Summer 2017 Event Image 29"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_030.jpg') }}" data-lightbox="image-30" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_030.jpg') }}" alt="Summer 2017 Event Image 30"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_031.jpg') }}" data-lightbox="image-31" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_031.jpg') }}" alt="Summer 2017 Event Image 31"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_032.jpg') }}" data-lightbox="image-32" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_032.jpg') }}" alt="Summer 2017 Event Image 32"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_033.jpg') }}" data-lightbox="image-33" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_033.jpg') }}" alt="Summer 2017 Event Image 33"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_034.jpg') }}" data-lightbox="image-34" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_034.jpg') }}" alt="Summer 2017 Event Image 34"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_035.jpg') }}" data-lightbox="image-35" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_035.jpg') }}" alt="Summer 2017 Event Image 35"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_036.jpg') }}" data-lightbox="image-36" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_036.jpg') }}" alt="Summer 2017 Event Image 36"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_037.jpg') }}" data-lightbox="image-37" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_037.jpg') }}" alt="Summer 2017 Event Image 37"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_038.jpg') }}" data-lightbox="image-38" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_038.jpg') }}" alt="Summer 2017 Event Image 38"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40 bottom-border">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_039.jpg') }}" data-lightbox="image-39" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_039.jpg') }}" alt="Summer 2017 Event Image 39"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_040.jpg') }}" data-lightbox="image-40" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_040.jpg') }}" alt="Summer 2017 Event Image 40"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_041.jpg') }}" data-lightbox="image-41" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_041.jpg') }}" alt="Summer 2017 Event Image 41"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_042.jpg') }}" data-lightbox="image-42" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_042.jpg') }}" alt="Summer 2017 Event Image 42"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_043.jpg') }}" data-lightbox="image-43" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_043.jpg') }}" alt="Summer 2017 Event Image 43"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_045.jpg') }}" data-lightbox="image-44" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_045.jpg') }}" alt="Summer 2017 Event Image 44"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_044.jpg') }}" data-lightbox="image-45" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_044.jpg') }}" alt="Summer 2017 Event Image 45"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_046.jpg') }}" data-lightbox="image-46" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_046.jpg') }}" alt="Summer 2017 Event Image 46"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_047.jpg') }}" data-lightbox="image-47" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_047.jpg') }}" alt="Summer 2017 Event Image 47"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_049.jpg') }}" data-lightbox="image-48" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_049.jpg') }}" alt="Summer 2017 Event Image 48" class="override"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_048.jpg') }}" data-lightbox="image-49" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_048.jpg') }}" alt="Summer 2017 Event Image 49"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_050.jpg') }}" data-lightbox="image-50" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_050.jpg') }}" alt="Summer 2017 Event Image 50"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_051.jpg') }}" data-lightbox="image-51" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_051.jpg') }}" alt="Summer 2017 Event Image 51"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_052.jpg') }}" data-lightbox="image-52" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_052.jpg') }}" alt="Summer 2017 Event Image 52"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_053.jpg') }}" data-lightbox="image-53" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_053.jpg') }}" alt="Summer 2017 Event Image 53"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_054.jpg') }}" data-lightbox="image-54" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_054.jpg') }}" alt="Summer 2017 Event Image 54"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_055.jpg') }}" data-lightbox="image-55" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_055.jpg') }}" alt="Summer 2017 Event Image 55"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_056.jpg') }}" data-lightbox="image-56" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_056.jpg') }}" alt="Summer 2017 Event Image 56"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_057.jpg') }}" data-lightbox="image-57" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_057.jpg') }}" alt="Summer 2017 Event Image 57"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40 bottom-border">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_058.jpg') }}" data-lightbox="image-58" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_058.jpg') }}" alt="Summer 2017 Event Image 58"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_059.jpg') }}" data-lightbox="image-59" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_059.jpg') }}" alt="Summer 2017 Event Image 59"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_060.jpg') }}" data-lightbox="image-60" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_060.jpg') }}" alt="Summer 2017 Event Image 60"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_061.jpg') }}" data-lightbox="image-61" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_061.jpg') }}" alt="Summer 2017 Event Image 61"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_062.jpg') }}" data-lightbox="image-62" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_062.jpg') }}" alt="Summer 2017 Event Image 62"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_063.jpg') }}" data-lightbox="image-63" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_063.jpg') }}" alt="Summer 2017 Event Image 63"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_064.jpg') }}" data-lightbox="image-64" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_064.jpg') }}" alt="Summer 2017 Event Image 64"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_065.jpg') }}" data-lightbox="image-65" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_065.jpg') }}" alt="Summer 2017 Event Image 65"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_066.jpg') }}" data-lightbox="image-66" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_066.jpg') }}" alt="Summer 2017 Event Image 66"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_067.jpg') }}" data-lightbox="image-67" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_067.jpg') }}" alt="Summer 2017 Event Image 67"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_068.jpg') }}" data-lightbox="image-68" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_068.jpg') }}" alt="Summer 2017 Event Image 68"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_069.jpg') }}" data-lightbox="image-69" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_069.jpg') }}" alt="Summer 2017 Event Image 69"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_070.jpg') }}" data-lightbox="image-70" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_070.jpg') }}" alt="Summer 2017 Event Image 70"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_071.jpg') }}" data-lightbox="image-71" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_071.jpg') }}" alt="Summer 2017 Event Image 71"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_072.jpg') }}" data-lightbox="image-72" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_072.jpg') }}" alt="Summer 2017 Event Image 72"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_073.jpg') }}" data-lightbox="image-73" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_073.jpg') }}" alt="Summer 2017 Event Image 73"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_074.jpg') }}" data-lightbox="image-74" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_074.jpg') }}" alt="Summer 2017 Event Image 74"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_075.jpg') }}" data-lightbox="image-75" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_075.jpg') }}" alt="Summer 2017 Event Image 75"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_076.jpg') }}" data-lightbox="image-76" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_076.jpg') }}" alt="Summer 2017 Event Image 76"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40 bottom-border">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_077.jpg') }}" data-lightbox="image-77" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_077.jpg') }}" alt="Summer 2017 Event Image 77"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_078.jpg') }}" data-lightbox="image-78" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_078.jpg') }}" alt="Summer 2017 Event Image 78"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_079.jpg') }}" data-lightbox="image-79" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_079.jpg') }}" alt="Summer 2017 Event Image 79"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_080.jpg') }}" data-lightbox="image-80" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_080.jpg') }}" alt="Summer 2017 Event Image 80"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_081.jpg') }}" data-lightbox="image-81" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_081.jpg') }}" alt="Summer 2017 Event Image 81"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_082.jpg') }}" data-lightbox="image-82" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_082.jpg') }}" alt="Summer 2017 Event Image 82"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_083.jpg') }}" data-lightbox="image-83" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_083.jpg') }}" alt="Summer 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_084.jpg') }}" data-lightbox="image-84" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_084.jpg') }}" alt="Summer 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_085.jpg') }}" data-lightbox="image-85" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_085.jpg') }}" alt="Summer 2017 Event Image 85"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_086.jpg') }}" data-lightbox="image-86" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_086.jpg') }}" alt="Summer 2017 Event Image 86"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_087.jpg') }}" data-lightbox="image-87" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_087.jpg') }}" alt="Summer 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_088.jpg') }}" data-lightbox="image-88" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_088.jpg') }}" alt="Summer 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_089.jpg') }}" data-lightbox="image-89" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_089.jpg') }}" alt="Summer 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_090.jpg') }}" data-lightbox="image-90" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_090.jpg') }}" alt="Summer 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_091.jpg') }}" data-lightbox="image-91" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_091.jpg') }}" alt="Summer 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_092.jpg') }}" data-lightbox="image-92" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_092.jpg') }}" alt="Summer 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_093.jpg') }}" data-lightbox="image-93" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_093.jpg') }}" alt="Summer 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_094.jpg') }}" data-lightbox="image-94" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_094.jpg') }}" alt="Summer 2017 Event Image 94"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_095.jpg') }}" data-lightbox="image-95" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_095.jpg') }}" alt="Summer 2017 Event Image 95"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_096.jpg') }}" data-lightbox="image-96" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_096.jpg') }}" alt="Summer 2017 Event Image 96"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_097.jpg') }}" data-lightbox="image-97" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_097.jpg') }}" alt="Summer 2017 Event Image 97"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_098.jpg') }}" data-lightbox="image-98" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_098.jpg') }}" alt="Summer 2017 Event Image 98"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_099.jpg') }}" data-lightbox="image-99" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_099.jpg') }}" alt="Summer 2017 Event Image 99"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_100.jpg') }}" data-lightbox="image-100" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_100.jpg') }}" alt="Summer 2017 Event Image 100"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_101.jpg') }}" data-lightbox="image-81" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_101.jpg') }}" alt="Summer 2017 Event Image 81"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_102.jpg') }}" data-lightbox="image-82" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_102.jpg') }}" alt="Summer 2017 Event Image 82"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_103.jpg') }}" data-lightbox="image-83" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_103.jpg') }}" alt="Summer 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_104.jpg') }}" data-lightbox="image-84" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_104.jpg') }}" alt="Summer 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_105.jpg') }}" data-lightbox="image-85" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_105.jpg') }}" alt="Summer 2017 Event Image 85"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_106.jpg') }}" data-lightbox="image-86" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_106.jpg') }}" alt="Summer 2017 Event Image 86"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_107.jpg') }}" data-lightbox="image-87" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_107.jpg') }}" alt="Summer 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_108.jpg') }}" data-lightbox="image-88" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_108.jpg') }}" alt="Summer 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_109.jpg') }}" data-lightbox="image-89" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_109.jpg') }}" alt="Summer 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_110.jpg') }}" data-lightbox="image-90" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_110.jpg') }}" alt="Summer 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_111.jpg') }}" data-lightbox="image-91" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_111.jpg') }}" alt="Summer 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_112.jpg') }}" data-lightbox="image-92" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_112.jpg') }}" alt="Summer 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_113.jpg') }}" data-lightbox="image-93" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_113.jpg') }}" alt="Summer 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_114.jpg') }}" data-lightbox="image-94" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_114.jpg') }}" alt="Summer 2017 Event Image 94"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_115.jpg') }}" data-lightbox="image-95" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_115.jpg') }}" alt="Summer 2017 Event Image 95"></a></li>
            </ul>
        </section>
        
        <section class="photo-section mb-40">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_116.jpg') }}" data-lightbox="image-96" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_116.jpg') }}" alt="Summer 2017 Event Image 96"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_117.jpg') }}" data-lightbox="image-97" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_117.jpg') }}" alt="Summer 2017 Event Image 97"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_118.jpg') }}" data-lightbox="image-98" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_118.jpg') }}" alt="Summer 2017 Event Image 98"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_119.jpg') }}" data-lightbox="image-99" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_119.jpg') }}" alt="Summer 2017 Event Image 99"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_120.jpg') }}" data-lightbox="image-100" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_120.jpg') }}" alt="Summer 2017 Event Image 100"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_121.jpg') }}" data-lightbox="image-81" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_121.jpg') }}" alt="Summer 2017 Event Image 81"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_122.jpg') }}" data-lightbox="image-82" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_122.jpg') }}" alt="Summer 2017 Event Image 82"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_123.jpg') }}" data-lightbox="image-83" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_123.jpg') }}" alt="Summer 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_124.jpg') }}" data-lightbox="image-84" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_124.jpg') }}" alt="Summer 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_125.jpg') }}" data-lightbox="image-85" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_125.jpg') }}" alt="Summer 2017 Event Image 85"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_126.jpg') }}" data-lightbox="image-86" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_126.jpg') }}" alt="Summer 2017 Event Image 86"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_127.jpg') }}" data-lightbox="image-87" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_127.jpg') }}" alt="Summer 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_128.jpg') }}" data-lightbox="image-88" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_128.jpg') }}" alt="Summer 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_129.jpg') }}" data-lightbox="image-89" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_129.jpg') }}" alt="Summer 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_130.jpg') }}" data-lightbox="image-90" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_130.jpg') }}" alt="Summer 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_131.jpg') }}" data-lightbox="image-91" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_131.jpg') }}" alt="Summer 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_132.jpg') }}" data-lightbox="image-92" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_132.jpg') }}" alt="Summer 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_133.jpg') }}" data-lightbox="image-93" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_133.jpg') }}" alt="Summer 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_134.jpg') }}" data-lightbox="image-94" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_134.jpg') }}" alt="Summer 2017 Event Image 94"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_135.jpg') }}" data-lightbox="image-95" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_135.jpg') }}" alt="Summer 2017 Event Image 95"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_136.jpg') }}" data-lightbox="image-96" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_136.jpg') }}" alt="Summer 2017 Event Image 96"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_137.jpg') }}" data-lightbox="image-97" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_137.jpg') }}" alt="Summer 2017 Event Image 97"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_138.jpg') }}" data-lightbox="image-98" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_138.jpg') }}" alt="Summer 2017 Event Image 98"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_139.jpg') }}" data-lightbox="image-99" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_139.jpg') }}" alt="Summer 2017 Event Image 99"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_140.jpg') }}" data-lightbox="image-100" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_140.jpg') }}" alt="Summer 2017 Event Image 100"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_141.jpg') }}" data-lightbox="image-81" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_141.jpg') }}" alt="Summer 2017 Event Image 81"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_142.jpg') }}" data-lightbox="image-82" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_142.jpg') }}" alt="Summer 2017 Event Image 82"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_143.jpg') }}" data-lightbox="image-83" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_143.jpg') }}" alt="Summer 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_144.jpg') }}" data-lightbox="image-84" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_144.jpg') }}" alt="Summer 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_145.jpg') }}" data-lightbox="image-85" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_145.jpg') }}" alt="Summer 2017 Event Image 85"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_146.jpg') }}" data-lightbox="image-86" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_146.jpg') }}" alt="Summer 2017 Event Image 86"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_147.jpg') }}" data-lightbox="image-87" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_147.jpg') }}" alt="Summer 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_148.jpg') }}" data-lightbox="image-88" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_148.jpg') }}" alt="Summer 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_149.jpg') }}" data-lightbox="image-89" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_149.jpg') }}" alt="Summer 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_150.jpg') }}" data-lightbox="image-90" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_150.jpg') }}" alt="Summer 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_151.jpg') }}" data-lightbox="image-91" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_151.jpg') }}" alt="Summer 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_152.jpg') }}" data-lightbox="image-92" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_152.jpg') }}" alt="Summer 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_153.jpg') }}" data-lightbox="image-93" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_153.jpg') }}" alt="Summer 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_154.jpg') }}" data-lightbox="image-94" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_154.jpg') }}" alt="Summer 2017 Event Image 94"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_155.jpg') }}" data-lightbox="image-95" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_155.jpg') }}" alt="Summer 2017 Event Image 95"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40">
            <h2 class="main-heading mb-40">2017 Summer Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_156.jpg') }}" data-lightbox="image-96" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_156.jpg') }}" alt="Summer 2017 Event Image 96"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_157.jpg') }}" data-lightbox="image-97" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_157.jpg') }}" alt="Summer 2017 Event Image 97"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_158.jpg') }}" data-lightbox="image-98" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_158.jpg') }}" alt="Summer 2017 Event Image 98"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_159.jpg') }}" data-lightbox="image-99" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_159.jpg') }}" alt="Summer 2017 Event Image 99"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_160.jpg') }}" data-lightbox="image-100" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_160.jpg') }}" alt="Summer 2017 Event Image 100"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_161.jpg') }}" data-lightbox="image-81" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_161.jpg') }}" alt="Summer 2017 Event Image 81"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_162.jpg') }}" data-lightbox="image-82" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_162.jpg') }}" alt="Summer 2017 Event Image 82"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_163.jpg') }}" data-lightbox="image-83" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_163.jpg') }}" alt="Summer 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_164.jpg') }}" data-lightbox="image-84" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_164.jpg') }}" alt="Summer 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_165.jpg') }}" data-lightbox="image-85" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_165.jpg') }}" alt="Summer 2017 Event Image 85"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_166.jpg') }}" data-lightbox="image-86" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_166.jpg') }}" alt="Summer 2017 Event Image 86"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_167.jpg') }}" data-lightbox="image-87" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_167.jpg') }}" alt="Summer 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_168.jpg') }}" data-lightbox="image-88" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_168.jpg') }}" alt="Summer 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_169.jpg') }}" data-lightbox="image-89" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_169.jpg') }}" alt="Summer 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_170.jpg') }}" data-lightbox="image-90" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_170.jpg') }}" alt="Summer 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_171.jpg') }}" data-lightbox="image-91" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_171.jpg') }}" alt="Summer 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_172.jpg') }}" data-lightbox="image-92" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_172.jpg') }}" alt="Summer 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_173.jpg') }}" data-lightbox="image-93" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_173.jpg') }}" alt="Summer 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_174.jpg') }}" data-lightbox="image-94" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_174.jpg') }}" alt="Summer 2017 Event Image 94"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_175.jpg') }}" data-lightbox="image-95" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_175.jpg') }}" alt="Summer 2017 Event Image 95"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_176.jpg') }}" data-lightbox="image-93" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_176.jpg') }}" alt="Summer 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_177.jpg') }}" data-lightbox="image-94" data-title="2017 Summer Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-summer-event/Uncorked_Fall2017_177.jpg') }}" alt="Summer 2017 Event Image 94"></a></li>
            </ul>
        </section>
    </div>
@stop