@extends('layout')

@section('banner')
    <div class="photos banner">
        <section class="small-wrapper">
            <h1 class="large-heading">{{ $pageName }}</h1>
        </section>
    </div>
@stop

@section('content')
    <div class="photos-nav">
        <div class="small-wrapper">
            <ul>
                <li class="active"><a href="/photos/2017-winter-event">2017 Winter Tasting</a></li>
                <li><a href="/photos/2016-summer-event">2016 Summer Tasting</a></li>
                <li><a href="/photos/2015-fall-event">2015 Fall Tasting</a></li>
                <li><a href="/photos/2015-fall-meeting">2015 Fall Committee Meeting</a></li>
                <li><a href="/photos/2015-winter-event">2015 Winter Tasting</a></li>
            </ul>
        </div>
    </div>
    <div class="small-wrapper photos-content">
        <section class="photo-section mb-40 mt-30 bottom-border">
            <h2 class="main-heading mb-40">2017 Summer Tasting</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_001.jpg') }}" data-lightbox="image-1" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_001.jpg') }}" alt="Winter 2017 Event Image 1"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_002.jpg') }}" data-lightbox="image-2" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_002.jpg') }}" alt="Winter 2017 Event Image 2"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_003.jpg') }}" data-lightbox="image-3" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_003.jpg') }}" alt="Winter 2017 Event Image 3"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_004.jpg') }}" data-lightbox="image-4" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_004.jpg') }}" alt="Winter 2017 Event Image 4"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_005.jpg') }}" data-lightbox="image-5" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_005.jpg') }}" alt="Winter 2017 Event Image 5"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_006.jpg') }}" data-lightbox="image-6" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_006.jpg') }}" alt="Winter 2017 Event Image 6"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_007.jpg') }}" data-lightbox="image-7" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_007.jpg') }}" alt="Winter 2017 Event Image 7"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_008.jpg') }}" data-lightbox="image-8" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_008.jpg') }}" alt="Winter 2017 Event Image 8"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_009.jpg') }}" data-lightbox="image-9" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_009.jpg') }}" alt="Winter 2017 Event Image 9"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_010.jpg') }}" data-lightbox="image-10" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_010.jpg') }}" alt="Winter 2017 Event Image 10"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_011.jpg') }}" data-lightbox="image-11" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_011.jpg') }}" alt="Winter 2017 Event Image 11"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_012.jpg') }}" data-lightbox="image-12" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_012.jpg') }}" alt="Winter 2017 Event Image 12"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_013.jpg') }}" data-lightbox="image-13" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_013.jpg') }}" alt="Winter 2017 Event Image 13"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_014.jpg') }}" data-lightbox="image-14" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_014.jpg') }}" alt="Winter 2017 Event Image 14"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_015.jpg') }}" data-lightbox="image-15" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_015.jpg') }}" alt="Winter 2017 Event Image 15"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_016.jpg') }}" data-lightbox="image-16" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_016.jpg') }}" alt="Winter 2017 Event Image 16"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_017.jpg') }}" data-lightbox="image-17" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_017.jpg') }}" alt="Winter 2017 Event Image 17"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_018.jpg') }}" data-lightbox="image-18" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_018.jpg') }}" alt="Winter 2017 Event Image 18"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_019.jpg') }}" data-lightbox="image-19" data-title="2017 Winter Tasting"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_019.jpg') }}" alt="Winter 2017 Event Image 19"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_020.jpg') }}" data-lightbox="image-20" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_020.jpg') }}" alt="Winter 2017 Event Image 20"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_021.jpg') }}" data-lightbox="image-21" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_021.jpg') }}" alt="Winter 2017 Event Image 21"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_022.jpg') }}" data-lightbox="image-22" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_022.jpg') }}" alt="Winter 2017 Event Image 22"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_023.jpg') }}" data-lightbox="image-23" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_023.jpg') }}" alt="Winter 2017 Event Image 23"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_024.jpg') }}" data-lightbox="image-24" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_024.jpg') }}" alt="Winter 2017 Event Image 24"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_025.jpg') }}" data-lightbox="image-25" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_025.jpg') }}" alt="Winter 2017 Event Image 25"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_026.jpg') }}" data-lightbox="image-26" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_026.jpg') }}" alt="Winter 2017 Event Image 26"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_027.jpg') }}" data-lightbox="image-27" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_027.jpg') }}" alt="Winter 2017 Event Image 27"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_028.jpg') }}" data-lightbox="image-28" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_028.jpg') }}" alt="Winter 2017 Event Image 28"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_029.jpg') }}" data-lightbox="image-29" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_029.jpg') }}" alt="Winter 2017 Event Image 29"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_030.jpg') }}" data-lightbox="image-30" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_030.jpg') }}" alt="Winter 2017 Event Image 30"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_031.jpg') }}" data-lightbox="image-31" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_031.jpg') }}" alt="Winter 2017 Event Image 31"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_032.jpg') }}" data-lightbox="image-32" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_032.jpg') }}" alt="Winter 2017 Event Image 32"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_033.jpg') }}" data-lightbox="image-33" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_033.jpg') }}" alt="Winter 2017 Event Image 33"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_034.jpg') }}" data-lightbox="image-34" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_034.jpg') }}" alt="Winter 2017 Event Image 34"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_035.jpg') }}" data-lightbox="image-35" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_035.jpg') }}" alt="Winter 2017 Event Image 35"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_036.jpg') }}" data-lightbox="image-36" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_036.jpg') }}" alt="Winter 2017 Event Image 36"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_037.jpg') }}" data-lightbox="image-37" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_037.jpg') }}" alt="Winter 2017 Event Image 37"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_038.jpg') }}" data-lightbox="image-38" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_038.jpg') }}" alt="Winter 2017 Event Image 38"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40 bottom-border">
            <h2 class="main-heading mb-40">2017 Winter Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_039.jpg') }}" data-lightbox="image-39" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_039.jpg') }}" alt="Winter 2017 Event Image 39"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_040.jpg') }}" data-lightbox="image-40" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_040.jpg') }}" alt="Winter 2017 Event Image 40"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_041.jpg') }}" data-lightbox="image-41" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_041.jpg') }}" alt="Winter 2017 Event Image 41"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_042.jpg') }}" data-lightbox="image-42" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_042.jpg') }}" alt="Winter 2017 Event Image 42"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_043.jpg') }}" data-lightbox="image-43" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_043.jpg') }}" alt="Winter 2017 Event Image 43"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_044.jpg') }}" data-lightbox="image-44" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_044.jpg') }}" alt="Winter 2017 Event Image 44"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_045.jpg') }}" data-lightbox="image-45" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_045.jpg') }}" alt="Winter 2017 Event Image 45"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_046.jpg') }}" data-lightbox="image-46" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_046.jpg') }}" alt="Winter 2017 Event Image 46"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_047.jpg') }}" data-lightbox="image-47" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_047.jpg') }}" alt="Winter 2017 Event Image 47"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_048.jpg') }}" data-lightbox="image-48" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_048.jpg') }}" alt="Winter 2017 Event Image 48"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_049.jpg') }}" data-lightbox="image-49" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_049.jpg') }}" alt="Winter 2017 Event Image 49"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_050.jpg') }}" data-lightbox="image-50" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_050.jpg') }}" alt="Winter 2017 Event Image 50"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_051.jpg') }}" data-lightbox="image-51" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_051.jpg') }}" alt="Winter 2017 Event Image 51"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_052.jpg') }}" data-lightbox="image-52" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_052.jpg') }}" alt="Winter 2017 Event Image 52"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_053.jpg') }}" data-lightbox="image-53" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_053.jpg') }}" alt="Winter 2017 Event Image 53"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_054.jpg') }}" data-lightbox="image-54" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_054.jpg') }}" alt="Winter 2017 Event Image 54"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_055.jpg') }}" data-lightbox="image-55" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_055.jpg') }}" alt="Winter 2017 Event Image 55"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_056.jpg') }}" data-lightbox="image-56" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_056.jpg') }}" alt="Winter 2017 Event Image 56"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_057.jpg') }}" data-lightbox="image-57" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_057.jpg') }}" alt="Winter 2017 Event Image 57"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40 bottom-border">
            <h2 class="main-heading mb-40">2017 Winter Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_058.jpg') }}" data-lightbox="image-58" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_058.jpg') }}" alt="Winter 2017 Event Image 58"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_059.jpg') }}" data-lightbox="image-59" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_059.jpg') }}" alt="Winter 2017 Event Image 59"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_060.jpg') }}" data-lightbox="image-60" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_060.jpg') }}" alt="Winter 2017 Event Image 60"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_061.jpg') }}" data-lightbox="image-61" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_061.jpg') }}" alt="Winter 2017 Event Image 61"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_062.jpg') }}" data-lightbox="image-62" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_062.jpg') }}" alt="Winter 2017 Event Image 62"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_063.jpg') }}" data-lightbox="image-63" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_063.jpg') }}" alt="Winter 2017 Event Image 63"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_064.jpg') }}" data-lightbox="image-64" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_064.jpg') }}" alt="Winter 2017 Event Image 64"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_065.jpg') }}" data-lightbox="image-65" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_065.jpg') }}" alt="Winter 2017 Event Image 65"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_066.jpg') }}" data-lightbox="image-66" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_066.jpg') }}" alt="Winter 2017 Event Image 66"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_067.jpg') }}" data-lightbox="image-67" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_067.jpg') }}" alt="Winter 2017 Event Image 67"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_068.jpg') }}" data-lightbox="image-68" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_068.jpg') }}" alt="Winter 2017 Event Image 68"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_069.jpg') }}" data-lightbox="image-69" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_069.jpg') }}" alt="Winter 2017 Event Image 69"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_070.jpg') }}" data-lightbox="image-70" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_070.jpg') }}" alt="Winter 2017 Event Image 70"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_071.jpg') }}" data-lightbox="image-71" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_071.jpg') }}" alt="Winter 2017 Event Image 71"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_072.jpg') }}" data-lightbox="image-72" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_072.jpg') }}" alt="Winter 2017 Event Image 72"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_073.jpg') }}" data-lightbox="image-73" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_073.jpg') }}" alt="Winter 2017 Event Image 73"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_074.jpg') }}" data-lightbox="image-74" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_074.jpg') }}" alt="Winter 2017 Event Image 74"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_075.jpg') }}" data-lightbox="image-75" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_075.jpg') }}" alt="Winter 2017 Event Image 75"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_076.jpg') }}" data-lightbox="image-76" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_076.jpg') }}" alt="Winter 2017 Event Image 76"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40 bottom-border">
            <h2 class="main-heading mb-40">2017 Winter Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_077.jpg') }}" data-lightbox="image-77" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_077.jpg') }}" alt="Winter 2017 Event Image 77"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_078.jpg') }}" data-lightbox="image-78" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_078.jpg') }}" alt="Winter 2017 Event Image 78"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_079.jpg') }}" data-lightbox="image-79" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_079.jpg') }}" alt="Winter 2017 Event Image 79"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_080.jpg') }}" data-lightbox="image-80" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_080.jpg') }}" alt="Winter 2017 Event Image 80"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_081.jpg') }}" data-lightbox="image-81" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_081.jpg') }}" alt="Winter 2017 Event Image 81"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_082.jpg') }}" data-lightbox="image-82" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_082.jpg') }}" alt="Winter 2017 Event Image 82"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_083.jpg') }}" data-lightbox="image-83" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_083.jpg') }}" alt="Winter 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_084.jpg') }}" data-lightbox="image-84" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_084.jpg') }}" alt="Winter 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_085.jpg') }}" data-lightbox="image-85" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_085.jpg') }}" alt="Winter 2017 Event Image 85"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_086.jpg') }}" data-lightbox="image-86" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_086.jpg') }}" alt="Winter 2017 Event Image 86"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_087.jpg') }}" data-lightbox="image-87" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_087.jpg') }}" alt="Winter 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_088.jpg') }}" data-lightbox="image-88" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_088.jpg') }}" alt="Winter 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_089.jpg') }}" data-lightbox="image-89" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_089.jpg') }}" alt="Winter 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_090.jpg') }}" data-lightbox="image-90" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_090.jpg') }}" alt="Winter 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_091.jpg') }}" data-lightbox="image-91" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_091.jpg') }}" alt="Winter 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_092.jpg') }}" data-lightbox="image-92" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_092.jpg') }}" alt="Winter 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_093.jpg') }}" data-lightbox="image-93" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_093.jpg') }}" alt="Winter 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_094.jpg') }}" data-lightbox="image-94" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_094.jpg') }}" alt="Winter 2017 Event Image 94"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_095.jpg') }}" data-lightbox="image-95" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_095.jpg') }}" alt="Winter 2017 Event Image 95"></a></li>
            </ul>
        </section>

        <section class="photo-section mb-40">
            <h2 class="main-heading mb-40">2017 Winter Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_096.jpg') }}" data-lightbox="image-96" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_096.jpg') }}" alt="Winter 2017 Event Image 96"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_097.jpg') }}" data-lightbox="image-97" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_097.jpg') }}" alt="Winter 2017 Event Image 97"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_098.jpg') }}" data-lightbox="image-98" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_098.jpg') }}" alt="Winter 2017 Event Image 98"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_099.jpg') }}" data-lightbox="image-99" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_099.jpg') }}" alt="Winter 2017 Event Image 99"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_100.jpg') }}" data-lightbox="image-100" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_100.jpg') }}" alt="Winter 2017 Event Image 100"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_101.jpg') }}" data-lightbox="image-81" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_101.jpg') }}" alt="Winter 2017 Event Image 81"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_102.jpg') }}" data-lightbox="image-82" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_102.jpg') }}" alt="Winter 2017 Event Image 82"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_103.jpg') }}" data-lightbox="image-83" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_103.jpg') }}" alt="Winter 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_104.jpg') }}" data-lightbox="image-84" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_104.jpg') }}" alt="Winter 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_105.jpg') }}" data-lightbox="image-85" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_105.jpg') }}" alt="Winter 2017 Event Image 85"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_106.jpg') }}" data-lightbox="image-86" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_106.jpg') }}" alt="Winter 2017 Event Image 86"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_107.jpg') }}" data-lightbox="image-87" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_107.jpg') }}" alt="Winter 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_108.jpg') }}" data-lightbox="image-88" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_108.jpg') }}" alt="Winter 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_109.jpg') }}" data-lightbox="image-89" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_109.jpg') }}" alt="Winter 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_110.jpg') }}" data-lightbox="image-90" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_110.jpg') }}" alt="Winter 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_111.jpg') }}" data-lightbox="image-91" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_111.jpg') }}" alt="Winter 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_112.jpg') }}" data-lightbox="image-92" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_112.jpg') }}" alt="Winter 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_113.jpg') }}" data-lightbox="image-93" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_113.jpg') }}" alt="Winter 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_114.jpg') }}" data-lightbox="image-94" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_114.jpg') }}" alt="Winter 2017 Event Image 94"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_115.jpg') }}" data-lightbox="image-95" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_115.jpg') }}" alt="Winter 2017 Event Image 95"></a></li>
            </ul>
        </section>
        
        <section class="photo-section mb-40">
            <h2 class="main-heading mb-40">2017 Winter Tasting Continued</h2>
            <ul class="photo-gallery-list">
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_116.jpg') }}" data-lightbox="image-96" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_116.jpg') }}" alt="Winter 2017 Event Image 96"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_117.jpg') }}" data-lightbox="image-97" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_117.jpg') }}" alt="Winter 2017 Event Image 97"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_118.jpg') }}" data-lightbox="image-98" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_118.jpg') }}" alt="Winter 2017 Event Image 98"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_119.jpg') }}" data-lightbox="image-99" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_119.jpg') }}" alt="Winter 2017 Event Image 99"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_120.jpg') }}" data-lightbox="image-100" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_120.jpg') }}" alt="Winter 2017 Event Image 100"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_121.jpg') }}" data-lightbox="image-81" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_121.jpg') }}" alt="Winter 2017 Event Image 81"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_122.jpg') }}" data-lightbox="image-82" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_122.jpg') }}" alt="Winter 2017 Event Image 82"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_123.jpg') }}" data-lightbox="image-83" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_123.jpg') }}" alt="Winter 2017 Event Image 83"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_124.jpg') }}" data-lightbox="image-84" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_124.jpg') }}" alt="Winter 2017 Event Image 84"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_125.jpg') }}" data-lightbox="image-85" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_125.jpg') }}" alt="Winter 2017 Event Image 85"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_126.jpg') }}" data-lightbox="image-86" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_126.jpg') }}" alt="Winter 2017 Event Image 86"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_127.jpg') }}" data-lightbox="image-87" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_127.jpg') }}" alt="Winter 2017 Event Image 87"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_128.jpg') }}" data-lightbox="image-88" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_128.jpg') }}" alt="Winter 2017 Event Image 88"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_129.jpg') }}" data-lightbox="image-89" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_129.jpg') }}" alt="Winter 2017 Event Image 89"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_130.jpg') }}" data-lightbox="image-90" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_130.jpg') }}" alt="Winter 2017 Event Image 90"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_131.jpg') }}" data-lightbox="image-91" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_131.jpg') }}" alt="Winter 2017 Event Image 91"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_132.jpg') }}" data-lightbox="image-92" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_132.jpg') }}" alt="Winter 2017 Event Image 92"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_133.jpg') }}" data-lightbox="image-93" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_133.jpg') }}" alt="Winter 2017 Event Image 93"></a></li>
                <li class="col-8"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_134.jpg') }}" data-lightbox="image-94" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_134.jpg') }}" alt="Winter 2017 Event Image 94"></a></li>
                <li class="col-16"><a href="{{ URL::asset('images/photos/2017-winter-event/Uncorked_135.jpg') }}" data-lightbox="image-95" data-title="2017 Event at the Gillespie"><img src="{{ URL::asset('images/vendor/unveil/loading-icon.gif') }}" data-src="{{ URL::asset('images/photos/2017-winter-event/Uncorked_135.jpg') }}" alt="Winter 2017 Event Image 95"></a></li>
            </ul>
        </section>
    </div>
@stop